[package]
name = "jq-repl"
version = "0.7.1"
edition = "2021"
description = "Interactively explore JSON with fzf and jq."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
clap = { version = "4.1.4", features = ["cargo", "deprecated", "derive", "env", "wrap_help"] }
shell-quote = "0.3.0"
tempfile = "3.3.0"
